#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 8080
COPY . .

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CodeManageMent.dll"]